server:
  port: 8989
spring:
  datasource:
    url: jdbc:sqlserver://mk-cideng.ddns.net:1433;databaseName=CRM
    username: sa
    password: M1tr4c1d3ngbarat
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: false
logging:
  level:
    org.springframework.security: TRACE
